### ISSUE TITLE
Getting `componentWillReceiveProps` of null

### ISSUE THREAD

**Issue by joshbedo** [FaridSafi/react-native-gifted-listview#18]
Trying to figure out how i can use redux to fetch the data from our API.. i had to add a callback to the action due to the restriction of passing state when its updated. Is there a better way to approach/fix this?

```
  _onFetch(page = 1, callback, options) {
    // if (!this.props.global.currentUser) return;
    this.props.actions.getApartments({}, (listings) => {
      return callback(listings)
    })
    // callback(this.state.listings)
  },
```

**Comment by joshbedo** [comment]
This was totally unrelated to anything with Gifted ListView i missed an import 0.0... weird error for something totally unrelated.

**Comment by faceyspacey** [comment]
@joshbedo how did you end up getting Redux to work with Gifted ListView? Was the callback to the action the correct approach? I feel like there could be a better more declarative way, possibly with `componentWillReceiveProps`, which might require further customization of Gifted ListView, but still might be the correct approach. 

...Because basically, this doesn't let you change the data in your redux store, i.e. from elsewhere in the app, and automatically have it update in the ListView. 

Imagine the list of rows is a user's blog articles, and he edits one. You will call a redux action and a reducer will update the store. However, GiftedListView will be out of sync. If GiftedListView used `componentWillReceiveProps` to be notified by Redux, it could then detect if the row is currently in the list, and then update the list. And in other async cases could display a spinner--i.e. redux sends GiftedListView a `loading: true` prop and then when an asynchronous action resolves, passes the data in another prop, while setting `loading: false`. 

@FaridSafi how would you want this implemented? I'll implement. ...btw, you get a chance to take a look at my PRs?

**Comment by KhalilZaidoun** [comment]
Can anyone write an implementation for this ?

**Comment by faceyspacey** [comment]
my implementation has it and much more:

https://github.com/faceyspacey/react-native-gifted-listview

**Comment by KhalilZaidoun** [comment]
thx for sharing but i have a big problem to use gifted listview with redux implementation. specifically ' load more ' , always onFetch method use the prev state. which proves a duplication of data

**Comment by faceyspacey** [comment]
i modified it quite a bit. As it is, it's not setup for Redux at all. Look at my recent commits and compare the code. Basically I receive a `rows` prop in `componentWillReceiveProps` **AND** a `fetchOptions` prop. When `fetchOptions` prop changes, `onFetch` is called again with the new options. your `onFetch` method should make the new request to get the rows from your server, and then store the rows in redux and then pass the rows via the `rows` prop back to _GiftedListView_. And voila! 

Paging is of course handled as well: the page # is incremented, and the same `fetchOptions` are passed.

**Comment by KhalilZaidoun** [comment]
hi @faceyspacey  see my example. my problem is still there 
https://gist.github.com/KhalilZaidoun/63b7b48fd34015419e537bbbaa2d8c45
